-- MySQL Script generated by MySQL Workbench
-- Tue Jul  2 18:27:22 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Employees
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Employees
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Employees` DEFAULT CHARACTER SET utf8 ;
USE `Employees` ;

-- -----------------------------------------------------
-- Table `Employees`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Employees`.`departments` (
  `dept_no` CHAR(4) NOT NULL,
  `dept_name` VARCHAR(40) NULL DEFAULT NULL,
  INDEX `dept_name` ())
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Employees`.`employess`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Employees`.`employess` (
  `emp_no` INT(11) NOT NULL,
  `birth_date` DATE NULL DEFAULT NULL,
  `firts_name` VARCHAR(14) NULL DEFAULT NULL,
  `last_name` VARCHAR(16) NULL DEFAULT NULL,
  `gender` ENUM('M', 'F') NULL DEFAULT NULL,
  `hire_date` DATE NULL DEFAULT NULL,
  INDEX `PRIMARY` ())
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Employees`.`dept_emp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Employees`.`dept_emp` (
  `emp_no` INT(11) NOT NULL,
  `dept_no` CHAR(4) NOT NULL,
  `from_date` DATE NULL DEFAULT NULL,
  `to_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`emp_no`, `dept_no`),
  INDEX `emp_no` (`dept_no` ASC),
  INDEX `dept_no` (),
  CONSTRAINT `fk_dept_no`
    FOREIGN KEY (`dept_no`)
    REFERENCES `Employees`.`departments` (`dept_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emp_no`
    FOREIGN KEY (`emp_no`)
    REFERENCES `Employees`.`employess` (`emp_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Employees`.`dept_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Employees`.`dept_manager` (
  `dept_no` CHAR(4) NOT NULL,
  `emp_no` INT(11) NOT NULL,
  `from_date` DATE NULL DEFAULT NULL,
  `to_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`dept_no`, `emp_no`),
  INDEX `emp_no` (`emp_no` ASC),
  INDEX `dept_no` (),
  CONSTRAINT `fk_dept_no`
    FOREIGN KEY (`dept_no`)
    REFERENCES `Employees`.`departments` (`dept_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emp_no`
    FOREIGN KEY (`emp_no`)
    REFERENCES `Employees`.`employess` (`emp_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Employees`.`salaries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Employees`.`salaries` (
  `emp_no` INT(11) NOT NULL,
  `salary` INT(11) NULL DEFAULT NULL,
  `from_date` DATE NOT NULL,
  `to_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`emp_no`, `from_date`),
  INDEX `emp_no` (),
  CONSTRAINT `fk_emp_no`
    FOREIGN KEY (`emp_no`)
    REFERENCES `Employees`.`employess` (`emp_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Employees`.`titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Employees`.`titles` (
  `emp_no` INT(11) NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `from_date` DATE NOT NULL,
  `to_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`emp_no`, `title`, `from_date`),
  INDEX `emp_no` (),
  CONSTRAINT `fk_emp_no`
    FOREIGN KEY (`emp_no`)
    REFERENCES `Employees`.`employess` (`emp_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
