-- MySQL Script generated by MySQL Workbench
-- 07/02/19 18:38:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema employees
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema employees
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `employees` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `employees` ;

-- -----------------------------------------------------
-- Table `employees`.`departements`
-- -----------------------------------------------------
CREATE TABLE IF EXISTS `employees`.`departements` (
  `dept_no` CHAR(4) NOT NULL COMMENT '',
  `dept_name` VARCHAR(40) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`dept_no`)  COMMENT '',
  INDEX `dept_name` ()  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `employees`.`employess`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees`.`employess` (
  `emp_no` INT(11) NOT NULL COMMENT '',
  `birth_date` DATE NULL DEFAULT NULL COMMENT '',
  `first_name` VARCHAR(14) NULL DEFAULT NULL COMMENT '',
  `last_name` VARCHAR(16) NULL DEFAULT NULL COMMENT '',
  `gender` ENUM('M','F') NULL DEFAULT NULL COMMENT '',
  `here_date` DATE NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`emp_no`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `employees`.`dept_emp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees`.`dept_emp` (
  `emp_no` INT(11) NOT NULL COMMENT '',
  `dept_no` CHAR(4) NOT NULL COMMENT '',
  `from_date` DATE NULL COMMENT '',
  `to_date` DATE NULL COMMENT '',
  PRIMARY KEY (`emp_no`, `dept_no`)  COMMENT '',
  INDEX `emp_no` ()  COMMENT '',
  INDEX `dept_no` ()  COMMENT '',
  CONSTRAINT `Fk_emp_no`
    FOREIGN KEY (`emp_no`)
    REFERENCES `employees`.`employess` (`emp_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_dept_no`
    FOREIGN KEY ()
    REFERENCES `employees`.`departements` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `employees`.`dept_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees`.`dept_manager` (
  `dept_no` CHAR(4) NOT NULL COMMENT '',
  `emp_no` INT(11) NOT NULL COMMENT '',
  `from_date` DATE NULL DEFAULT NULL COMMENT '',
  `to_date` DATE NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`dept_no`, `emp_no`)  COMMENT '',
  INDEX `emp_no` (`emp_no` ASC)  COMMENT '',
  INDEX `dept_no` ()  COMMENT '',
  CONSTRAINT `Fk_dept_no`
    FOREIGN KEY (`dept_no`)
    REFERENCES `employees`.`departements` (`dept_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_emp_no`
    FOREIGN KEY (`emp_no`)
    REFERENCES `employees`.`employess` (`emp_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `employees`.`salaries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees`.`salaries` (
  `emp_no` INT(11) NOT NULL COMMENT '',
  `salary` INT(11) NULL DEFAULT NULL COMMENT '',
  `from_date` DATE NOT NULL COMMENT '',
  `to_date` DATE NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`emp_no`, `from_date`)  COMMENT '',
  INDEX `emp_no` ()  COMMENT '',
  CONSTRAINT `Fk_emp_no`
    FOREIGN KEY (`emp_no`)
    REFERENCES `employees`.`employess` (`emp_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `employees`.`titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees`.`titles` (
  `emp_no` INT(11) NOT NULL COMMENT '',
  `title` VARCHAR(50) NOT NULL COMMENT '',
  `from_date` DATE NOT NULL COMMENT '',
  `to_date` DATE NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`emp_no`, `title`, `from_date`)  COMMENT '',
  INDEX `emp_no` ()  COMMENT '',
  CONSTRAINT `Fk_emp_no`
    FOREIGN KEY (`emp_no`)
    REFERENCES `employees`.`employess` (`emp_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
