-- MySQL Script generated by MySQL Workbench
-- Tue Jul  2 18:27:33 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`departements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departements` (
  `dept_no` CHAR(4) NOT NULL,
  `dept_name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`dept_no`),
  INDEX `dept_name` (`dept_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employees` (
  `emp_no` INT(11) NOT NULL,
  `birth_date` DATE NOT NULL,
  `first_name` VARCHAR(14) NOT NULL,
  `last_name` VARCHAR(16) NOT NULL,
  `gender` ENUM('M', 'F') NOT NULL,
  `hire_date` DATE NOT NULL,
  PRIMARY KEY (`emp_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dept_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dept_manager` (
  `dept_no` CHAR(4) NOT NULL,
  `emp_no` INT(11) NOT NULL,
  `form_date` DATE NOT NULL,
  `to_date` DATE NOT NULL,
  PRIMARY KEY (`dept_no`, `emp_no`),
  INDEX `emp_no` (),
  INDEX `dept_no` (`emp_no` ASC),
  CONSTRAINT `fk_dept_departements`
    FOREIGN KEY (`dept_no`)
    REFERENCES `mydb`.`departements` (`dept_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `emp_no`
    FOREIGN KEY (`emp_no`)
    REFERENCES `mydb`.`employees` (`emp_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`salaries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`salaries` (
  `emp_no` INT(11) NOT NULL,
  `salary` INT(11) NOT NULL,
  `form_date` DATE NOT NULL,
  `to_date` DATE NOT NULL,
  PRIMARY KEY (`emp_no`, `form_date`),
  INDEX `emp_no` (),
  CONSTRAINT `fk_emp_no`
    FOREIGN KEY (`emp_no`)
    REFERENCES `mydb`.`employees` (`emp_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`titles` (
  `emp_no` INT(11) NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `from_date` DATE NOT NULL,
  `to_date` DATE NULL,
  PRIMARY KEY (`emp_no`, `title`, `from_date`),
  INDEX `emp_no` (),
  CONSTRAINT `fk_emp`
    FOREIGN KEY (`emp_no`)
    REFERENCES `mydb`.`employees` (`emp_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dept_emp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dept_emp` (
  `emp_no` INT(11) NOT NULL,
  `dept_no` CHAR(4) NOT NULL,
  `form_date` DATE NOT NULL,
  `to_date` DATE NOT NULL,
  PRIMARY KEY (`emp_no`, `dept_no`),
  INDEX `emp_no` (`emp_no` ASC),
  INDEX `dept_no` (`dept_no` ASC),
  CONSTRAINT `fk_dept_emp_employees10`
    FOREIGN KEY (`emp_no`)
    REFERENCES `mydb`.`employees` (`emp_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dept_dept_departements0`
    FOREIGN KEY (`dept_no`)
    REFERENCES `mydb`.`departements` (`dept_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
